import type { Logger, Plugin, ViteDevServer } from 'vite';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { styleText } from 'node:util';
import { normalizePath } from 'vite';
import picomatch from 'picomatch';

const VIRTUAL_MODULE_ID = 'virtual:static-assets';
const RESOLVED_VIRTUAL_MODULE_ID = '\0virtual:static-assets';

interface StaticAssetsPluginOptions {
  /**
   * Directory to scan for static assets
   * @default "public"
   */
  directory?: string;
  /**
   * @deprecated Use `typesOutputFile` instead. This option will be removed in a future version.
   */
  outputFile?: string;
  /**
   * Output file for the generated .d.ts type definitions
   * @default "src/static-assets.d.ts"
   */
  typesOutputFile?: string;
  /**
   * Array of glob patterns to ignore
   * @default [".DS_Store"]
   */
  ignore?: string[];
  /**
   * Debounce time in milliseconds for file system events
   * @default 200
   */
  debounce?: number;
  /**
   * Enable generation of directory types and helper functions
   * @default true
   */
  enableDirectoryTypes?: boolean;
  /**
   * Maximum directory nesting level for type generation
   * @default 5
   */
  maxDirectoryDepth?: number;
  /**
   * Whether to allow referencing empty directories in transform hook validation
   * @default false
   */
  allowEmptyDirectories?: boolean;
  /**
   * @deprecated No longer needed — base URL is handled automatically via import.meta.env.BASE_URL.
   */
  addLeadingSlash?: boolean;
}

/**
 * Asynchronously scan a directory and return all file paths (using Vite's normalizePath).
 *
 * Guards against symlink loops by tracking the real paths of *ancestors on the
 * current recursion path*. Two sibling symlinks pointing at the same target
 * (e.g. `public/brand-a -> shared/`, `public/brand-b -> shared/`) are still
 * walked independently — only a cycle (entering an ancestor) is rejected.
 *
 * The `_ancestors` parameter is internal — callers should not pass it.
 */
async function getAllFiles(
  dir: string,
  baseDir: string,
  isIgnored: (path: string) => boolean,
  _ancestors?: ReadonlySet<string>
): Promise<string[]> {
  const ancestors = _ancestors ?? new Set<string>();
  let realDir: string;
  try {
    realDir = await fs.promises.realpath(dir);
  } catch {
    realDir = dir;
  }
  if (ancestors.has(realDir)) {
    console.warn(`${styleText('yellow', '⚠')} Symlink loop detected at ${dir} (real path ${realDir}); skipping.`);
    return [];
  }
  // Each child gets a fresh ancestor set that includes this directory. Siblings
  // do NOT share the set, so legitimate aliases pointing at the same target
  // are walked separately.
  const childAncestors = new Set(ancestors);
  childAncestors.add(realDir);

  try {
    const items = await fs.promises.readdir(dir);

    const itemPromises = items.map(async (item) => {
      try {
        const fullPath = path.join(dir, item);
        const relativePath = normalizePath(path.relative(baseDir, fullPath));

        if (isIgnored(relativePath)) {
          return [];
        }

        const stat = await fs.promises.stat(fullPath);

        if (stat.isDirectory()) {
          return getAllFiles(fullPath, baseDir, isIgnored, childAncestors);
        }
        return [relativePath];
      } catch (err) {
        console.warn(`${styleText('yellow', '⚠')} Error processing item ${item}: ${err instanceof Error ? err.message : err}`);
        return [];
      }
    });

    const nestedResults = await Promise.all(itemPromises);
    return nestedResults.flat();
  } catch (err) {
    const error = err as NodeJS.ErrnoException;
    if (error.code !== 'ENOENT') {
      console.error(`${styleText('red', '✗')} Error reading directory ${dir}: ${err instanceof Error ? err.message : err}`);
    }
    return [];
  }
}

/**
 * Extracts directory paths from a list of file paths.
 * Uses '.' to represent the root directory.
 */
function extractDirectories(files: string[], maxDepth = 5): Set<string> {
  const directories = new Set<string>();
  let hasRootFiles = false;

  for (const file of files) {
    const dirPath = path.posix.dirname(file);

    if (dirPath === '.') {
      hasRootFiles = true;
      continue;
    }

    const parts = dirPath.split('/');
    let currentPath = '';

    for (let i = 0; i < Math.min(parts.length, maxDepth); i++) {
      if (parts[i] === '') continue;
      currentPath += `${parts[i]}/`;
      directories.add(currentPath);
    }
  }

  if (hasRootFiles) {
    directories.add('.');
  }

  return directories;
}

/**
 * Generates the runtime JavaScript code for the virtual module.
 * Uses import.meta.env.BASE_URL for proper base path handling.
 */
function generateVirtualModuleCode(files: string[]): string {
  const sortedFiles = [...files].sort();

  // JSON.stringify gives a valid JS string literal that escapes quotes,
  // backslashes, control chars, and unicode safely.
  return `// Virtual module generated by vite-static-assets-plugin

const assets = new Set([
${sortedFiles.map(file => `  ${JSON.stringify(file)}`).join(',\n')}
]);

export function staticAssets(path) {
  if (!assets.has(path)) {
    throw new Error(
      \`Static asset "\${path}" does not exist in static assets directory\`
    );
  }
  return \`\${import.meta.env.BASE_URL}\${path}\`;
}
`;
}

/**
 * Generates the .d.ts file content with declare module for virtual:static-assets.
 */
function generateDtsCode(
  files: string[],
  options: StaticAssetsPluginOptions = {}
): string {
  const {
    enableDirectoryTypes = true,
    maxDirectoryDepth = 5,
  } = options;

  const sortedFiles = [...files].sort();

  // JSON.stringify produces a valid TS string literal type token (TS accepts
  // double-quoted literals, and properly escapes special characters).
  const fileList = sortedFiles.length > 0
    ? sortedFiles.map(file => `    ${JSON.stringify(file)}`).join(' |\n')
    : '    never';

  let directoryTypesCode = '';

  if (enableDirectoryTypes) {
    const directories = extractDirectories(sortedFiles, maxDirectoryDepth);

    if (directories.size > 0 || sortedFiles.some(f => !f.includes('/'))) {
      const directoryList = Array.from(directories)
        .sort()
        .map(dir => `    ${JSON.stringify(dir)}`)
        .join(' |\n');

      const staticAssetDirectoryType = directoryList.length > 0 ? directoryList : '    never';

      directoryTypesCode = `
  /**
   * Represents the known directories containing static assets.
   * '.' represents the root directory.
   */
  export type StaticAssetDirectory =
${staticAssetDirectoryType};

  /**
   * Represents the relative paths of files located *directly* within a specific directory.
   * Use '.' for the root directory.
   * @template Dir - A directory path string literal type from StaticAssetDirectory.
   */
  export type FilesInFolder<Dir extends '.' | StaticAssetDirectory> =
    Dir extends '.'
      ? Exclude<StaticAssetPath, \`\${string}/\${string}\`>
      : Extract<StaticAssetPath, \`\${Dir}\${string}\`> extends infer Match
        ? Match extends \`\${Dir}\${infer FileName}\`
          ? FileName extends \`\${string}/\${string}\`
            ? never
            : Match
          : never
        : never;
`;
    }
  }

  return `// Auto-generated by vite-static-assets-plugin. Do not edit.
declare module 'virtual:static-assets' {
  export type StaticAssetPath =
${fileList};
${directoryTypesCode}
  /**
   * Gets the URL for a specific static asset
   * @param path Path to the asset
   * @returns The URL for the asset
   */
  export function staticAssets(path: StaticAssetPath): string;
}
`;
}

/**
 * Validates asset references in source code using regex.
 * Returns an error message if a missing asset is found, or null if all references are valid.
 *
 * Note: The regex approach can match inside comments or string literals.
 * This is a known limitation — false positives are rare in practice.
 */
function validateAssetReferences(
  code: string,
  id: string,
  currentFiles: Set<string>,
  directory: string,
  options: StaticAssetsPluginOptions = {}
): string | null {
  const enableDirectoryTypes = options.enableDirectoryTypes !== false;

  const staticAssetsRegex = /staticAssets\s*\(\s*['"]([^'"]+)['"]\s*\)/g;
  for (const match of code.matchAll(staticAssetsRegex)) {
    const assetPath = match[1];
    if (!currentFiles.has(assetPath)) {
      const relativeId = normalizePath(path.relative(process.cwd(), id));
      const relativeDir = normalizePath(path.relative(process.cwd(), directory));
      return `\n\n${styleText('red', 'Error:')} Static asset: ${styleText('yellowBright', assetPath)}\n  Referenced in: ${styleText('cyan', relativeId)}\n  Asset not found in scanned directory: ${styleText('blue', relativeDir)}\n\n  Please ensure the asset exists and the path is correct.\n`;
    }
  }

  if (enableDirectoryTypes) {
    const staticAssetsDirRegex = /staticAssetsFromDir\s*\(\s*['"]([^'"]+)['"]\s*\)/g;
    for (const dirMatch of code.matchAll(staticAssetsDirRegex)) {
      const dirPath = dirMatch[1];
      let hasAssetsInDir = false;

      if (dirPath === '.') {
        hasAssetsInDir = Array.from(currentFiles).some(file => !file.includes('/'));
      } else {
        const normalizedPath = path.posix.normalize(dirPath);
        const dirPathWithSlash = normalizedPath.endsWith('/') ? normalizedPath : `${normalizedPath}/`;
        hasAssetsInDir = Array.from(currentFiles).some(file => file.startsWith(dirPathWithSlash));
      }

      if (!hasAssetsInDir && options.allowEmptyDirectories !== true) {
        const relativeId = normalizePath(path.relative(process.cwd(), id));
        const relativeDir = normalizePath(path.relative(process.cwd(), directory));
        return `\n\n${styleText('red', 'Error:')} Static asset directory: ${styleText('yellowBright', dirPath)}\n  Referenced in: ${styleText('cyan', relativeId)}\n  Directory is empty or does not exist in scanned directory: ${styleText('blue', relativeDir)}\n\n  Ensure the directory contains assets or set 'allowEmptyDirectories: true'.\n`;
      }
    }
  }

  return null;
}

// Export pure functions for testing
export { getAllFiles, extractDirectories, generateVirtualModuleCode, generateDtsCode, validateAssetReferences };

// --- Main Plugin Function ---

export default function staticAssetsPlugin(options: StaticAssetsPluginOptions = {}): Plugin {
  const directory = path.resolve(process.cwd(), options.directory || 'public');
  const ignorePatterns = options.ignore || ['.DS_Store'];
  const enableDirectoryTypes = options.enableDirectoryTypes !== false;
  const isIgnored = picomatch(ignorePatterns, { dot: true });

  // Resolve typesOutputFile, with deprecation fallback from outputFile
  let typesOutputFile: string;
  if (options.typesOutputFile) {
    typesOutputFile = path.resolve(process.cwd(), options.typesOutputFile);
  } else if (options.outputFile) {
    console.warn(`${styleText('yellow', '⚠')} [vite-plugin-static-assets] 'outputFile' is deprecated. Use 'typesOutputFile' instead. The plugin now generates a .d.ts file, not a .ts file.`);
    // Derive .d.ts path from old outputFile
    const oldPath = options.outputFile;
    typesOutputFile = path.resolve(process.cwd(), oldPath.replace(/\.ts$/, '.d.ts'));
  } else {
    typesOutputFile = path.resolve(process.cwd(), 'src/static-assets.d.ts');
  }

  if (options.addLeadingSlash !== undefined) {
    console.warn(`${styleText('yellow', '⚠')} [vite-plugin-static-assets] 'addLeadingSlash' is deprecated and ignored. Base URL is now handled automatically via import.meta.env.BASE_URL.`);
  }

  // State
  let currentFiles: Set<string> = new Set();
  let debounceTimer: ReturnType<typeof setTimeout> | null = null;
  let server: ViteDevServer | null = null;
  let logger: Logger | null = null;
  const info = (msg: string) => {
    if (logger) logger.info(msg);
    else console.log(msg);
  };
  const warn = (msg: string) => {
    if (logger) logger.warn(msg);
    else console.warn(msg);
  };

  const writeDtsFile = async (files: string[]) => {
    const dtsCode = generateDtsCode(files, { ...options, enableDirectoryTypes });
    const outputDir = path.dirname(typesOutputFile);
    await fs.promises.mkdir(outputDir, { recursive: true });

    // Only write if content changed
    const currentContent = await fs.promises.readFile(typesOutputFile, 'utf-8').catch(() => '');
    if (currentContent !== dtsCode) {
      await fs.promises.writeFile(typesOutputFile, dtsCode);
      return true;
    }
    return false;
  };

  return {
    name: 'vite-plugin-static-assets',

    configResolved(resolvedConfig) {
      logger = resolvedConfig.logger;
    },

    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID;
      }
    },

    load(id) {
      if (id === RESOLVED_VIRTUAL_MODULE_ID) {
        return generateVirtualModuleCode([...currentFiles]);
      }
    },

    async buildStart() {
      try {
        // Stat the source. ENOENT is a soft warning (some workflows scan a
        // directory that doesn't exist yet); any other access error or a
        // non-directory target is a hard failure — silently emitting empty
        // types would hide the misconfiguration.
        let sourceExists = false;
        try {
          const stat = await fs.promises.stat(directory);
          if (!stat.isDirectory()) {
            throw new Error(
              `[vite-plugin-static-assets] 'directory' option "${options.directory || 'public'}" is not a directory.`,
            );
          }
          sourceExists = true;
        } catch (e) {
          const error = e as NodeJS.ErrnoException;
          if (error.code === 'ENOENT') {
            warn(`${styleText('yellow', '⚠')} [vite-plugin-static-assets] Source directory "${options.directory || 'public'}" not found. Generating empty types.`);
            currentFiles = new Set();
          } else {
            throw e;
          }
        }

        // Scan files
        const files = sourceExists ? await getAllFiles(directory, directory, isIgnored) : [];

        currentFiles = new Set(files);

        // Write .d.ts file
        await writeDtsFile(files);
        info(`${styleText('green', '✓')} Generated static assets types at ${styleText('blue', normalizePath(path.relative(process.cwd(), typesOutputFile)))} (${currentFiles.size} assets)`);
      } catch (err) {
        console.error(`${styleText('red', '✗')} [vite-plugin-static-assets] Error during buildStart: ${err instanceof Error ? err.message : err}`);
        throw err;
      }
    },

    transform(code: string, id: string) {
      // Skip node_modules and the virtual module itself
      if (id.includes('node_modules') || id === RESOLVED_VIRTUAL_MODULE_ID) {
        return null;
      }
      // Only process relevant files. Covers JS/TS (with esm/cjs variants),
      // Vue/Svelte SFCs, and Astro/MDX components.
      if (!/\.(?:[mc]?[jt]sx?|vue|svelte|astro|mdx)$/.test(id)) {
        return null;
      }

      const error = validateAssetReferences(code, id, currentFiles, directory, options);
      if (error) {
        console.error(error);
        throw new Error(error);
      }

      return null;
    },

    configureServer(devServer) {
      server = devServer;

      // Use Vite's built-in watcher instead of a separate chokidar instance
      server.watcher.add(directory);

      const handleChange = async () => {
        if (debounceTimer) clearTimeout(debounceTimer);
        debounceTimer = setTimeout(async () => {
          try {
            info(`${styleText('cyan', 'ℹ')} [vite-plugin-static-assets] Change detected, regenerating types...`);
            const updatedFiles = await getAllFiles(directory, directory, isIgnored);
            const newFileSet = new Set(updatedFiles);

            // Short-circuit if file set hasn't changed
            if (newFileSet.size === currentFiles.size && [...newFileSet].every(f => currentFiles.has(f))) {
              info(`${styleText('gray', '✓')} [vite-plugin-static-assets] No changes in asset set.`);
              return;
            }

            currentFiles = newFileSet;

            // Regenerate .d.ts
            await writeDtsFile(updatedFiles);

            // Invalidate the virtual module so Vite re-loads it
            const mod = server!.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID);
            if (mod) {
              server!.moduleGraph.invalidateModule(mod);
            }
            server!.ws.send({ type: 'full-reload' });

            info(`${styleText('green', '✓')} Updated static assets type definitions — ${currentFiles.size} assets.`);
          } catch (err) {
            console.error(`${styleText('red', '✗')} Error updating static assets: ${err instanceof Error ? err.message : err}`);
          }
        }, options.debounce ?? 200);
      };

      server.watcher.on('add', handleChange);
      server.watcher.on('unlink', handleChange);
      server.watcher.on('change', handleChange);
      server.watcher.on('addDir', handleChange);
      server.watcher.on('unlinkDir', handleChange);

      info(`${styleText('cyan', 'ℹ')} [vite-plugin-static-assets] Watching for changes in ${styleText('blue', normalizePath(path.relative(process.cwd(), directory)))}`);
    },

    buildEnd() {
      if (debounceTimer) {
        clearTimeout(debounceTimer);
        debounceTimer = null;
      }
    },
  };
}
