import type { Logger, Plugin, ViteDevServer } from 'vite';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { styleText } from 'node:util';
import { normalizePath } from 'vite';
import picomatch from 'picomatch';

const VIRTUAL_MODULE_ID = 'virtual:static-assets';
const RESOLVED_VIRTUAL_MODULE_ID = '\0virtual:static-assets';

export interface StaticAssetsPluginOptions {
  /**
   * Directory to scan for static assets
   * @default "public"
   */
  directory?: string;
  /**
   * @deprecated Use `typesOutputFile` instead. This option will be removed in a future version.
   */
  outputFile?: string;
  /**
   * Output file for the generated .d.ts type definitions
   * @default "src/static-assets.d.ts"
   */
  typesOutputFile?: string;
  /**
   * Array of glob patterns to ignore
   * @default [".DS_Store"]
   */
  ignore?: string[];
  /**
   * Debounce time in milliseconds for file system events
   * @default 200
   */
  debounce?: number;
  /**
   * Enable generation of directory types and helper functions
   * @default true
   */
  enableDirectoryTypes?: boolean;
  /**
   * Maximum directory nesting level for type generation
   * @default 5
   */
  maxDirectoryDepth?: number;
  /**
   * @deprecated No longer needed — base URL is handled automatically via import.meta.env.BASE_URL.
   */
  addLeadingSlash?: boolean;
}

/**
 * Asynchronously scan a directory and return all file paths (using Vite's normalizePath).
 *
 * Guards against symlink loops by tracking the real paths of *ancestors on the
 * current recursion path*. Two sibling symlinks pointing at the same target
 * (e.g. `public/brand-a -> shared/`, `public/brand-b -> shared/`) are still
 * walked independently — only a cycle (entering an ancestor) is rejected.
 *
 * The `_ancestors` parameter is internal — callers should not pass it.
 */
async function getAllFiles(
  dir: string,
  baseDir: string,
  isIgnored: (path: string) => boolean,
  _ancestors?: ReadonlySet<string>
): Promise<string[]> {
  const ancestors = _ancestors ?? new Set<string>();
  let realDir: string;
  try {
    realDir = await fs.promises.realpath(dir);
  } catch {
    realDir = dir;
  }
  if (ancestors.has(realDir)) {
    console.warn(`${styleText('yellow', '⚠')} Symlink loop detected at ${dir} (real path ${realDir}); skipping.`);
    return [];
  }
  // Each child gets a fresh ancestor set that includes this directory. Siblings
  // do NOT share the set, so legitimate aliases pointing at the same target
  // are walked separately.
  const childAncestors = new Set(ancestors);
  childAncestors.add(realDir);

  try {
    const items = await fs.promises.readdir(dir);

    const itemPromises = items.map(async (item) => {
      try {
        const fullPath = path.join(dir, item);
        const relativePath = normalizePath(path.relative(baseDir, fullPath));

        if (isIgnored(relativePath)) {
          return [];
        }

        const stat = await fs.promises.stat(fullPath);

        if (stat.isDirectory()) {
          return getAllFiles(fullPath, baseDir, isIgnored, childAncestors);
        }
        return [relativePath];
      } catch (err) {
        console.warn(`${styleText('yellow', '⚠')} Error processing item ${item}: ${err instanceof Error ? err.message : err}`);
        return [];
      }
    });

    const nestedResults = await Promise.all(itemPromises);
    return nestedResults.flat();
  } catch (err) {
    const error = err as NodeJS.ErrnoException;
    if (error.code !== 'ENOENT') {
      console.error(`${styleText('red', '✗')} Error reading directory ${dir}: ${err instanceof Error ? err.message : err}`);
    }
    return [];
  }
}

/**
 * Extracts directory paths from a list of file paths.
 * Uses '.' to represent the root directory.
 */
function extractDirectories(files: string[], maxDepth = 5): Set<string> {
  const directories = new Set<string>();
  let hasRootFiles = false;

  for (const file of files) {
    const dirPath = path.posix.dirname(file);

    if (dirPath === '.') {
      hasRootFiles = true;
      continue;
    }

    const parts = dirPath.split('/');
    let currentPath = '';

    for (let i = 0; i < Math.min(parts.length, maxDepth); i++) {
      if (parts[i] === '') continue;
      currentPath += `${parts[i]}/`;
      directories.add(currentPath);
    }
  }

  if (hasRootFiles) {
    directories.add('.');
  }

  return directories;
}

/**
 * Generates the runtime JavaScript code for the virtual module.
 * Uses import.meta.env.BASE_URL for proper base path handling.
 */
function generateVirtualModuleCode(files: string[]): string {
  const sortedFiles = [...files].sort();

  // JSON.stringify gives a valid JS string literal that escapes quotes,
  // backslashes, control chars, and unicode safely.
  return `// Virtual module generated by vite-static-assets-plugin

const assets = new Set([
${sortedFiles.map(file => `  ${JSON.stringify(file)}`).join(',\n')}
]);

export function staticAssets(path) {
  if (!assets.has(path)) {
    throw new Error(
      \`Static asset "\${path}" does not exist in static assets directory\`
    );
  }
  return \`\${import.meta.env.BASE_URL}\${path}\`;
}
`;
}

/**
 * Generates the .d.ts file content with declare module for virtual:static-assets.
 */
function generateDtsCode(
  files: string[],
  options: StaticAssetsPluginOptions = {}
): string {
  const {
    enableDirectoryTypes = true,
    maxDirectoryDepth = 5,
  } = options;

  const sortedFiles = [...files].sort();

  // JSON.stringify produces a valid TS string literal type token (TS accepts
  // double-quoted literals, and properly escapes special characters).
  const fileList = sortedFiles.length > 0
    ? sortedFiles.map(file => `    ${JSON.stringify(file)}`).join(' |\n')
    : '    never';

  let directoryTypesCode = '';

  if (enableDirectoryTypes) {
    const directories = extractDirectories(sortedFiles, maxDirectoryDepth);

    if (directories.size > 0 || sortedFiles.some(f => !f.includes('/'))) {
      const directoryList = Array.from(directories)
        .sort()
        .map(dir => `    ${JSON.stringify(dir)}`)
        .join(' |\n');

      const staticAssetDirectoryType = directoryList.length > 0 ? directoryList : '    never';

      directoryTypesCode = `
  /**
   * Represents the known directories containing static assets.
   * '.' represents the root directory.
   */
  export type StaticAssetDirectory =
${staticAssetDirectoryType};

  /**
   * Represents the relative paths of files located *directly* within a specific directory.
   * Use '.' for the root directory.
   * @template Dir - A directory path string literal type from StaticAssetDirectory.
   */
  export type FilesInFolder<Dir extends '.' | StaticAssetDirectory> =
    Dir extends '.'
      ? Exclude<StaticAssetPath, \`\${string}/\${string}\`>
      : Extract<StaticAssetPath, \`\${Dir}\${string}\`> extends infer Match
        ? Match extends \`\${Dir}\${infer FileName}\`
          ? FileName extends \`\${string}/\${string}\`
            ? never
            : Match
          : never
        : never;
`;
    }
  }

  return `// Auto-generated by vite-static-assets-plugin. Do not edit.
declare module 'virtual:static-assets' {
  export type StaticAssetPath =
${fileList};
${directoryTypesCode}
  /**
   * Gets the URL for a specific static asset
   * @param path Path to the asset
   * @returns The URL for the asset
   */
  export function staticAssets(path: StaticAssetPath): string;
}
`;
}

/**
 * Validates asset references in source code using regex.
 * Returns an error message if a missing asset is found, or null if all references are valid.
 *
 * Note: The regex approach can match inside comments or string literals.
 * This is a known limitation — false positives are rare in practice.
 */
function validateAssetReferences(
  code: string,
  id: string,
  currentFiles: Set<string>,
  directory: string,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  _options: StaticAssetsPluginOptions = {}
): string | null {
  // Two alternations, one per quote style, so we track which quote opened the
  // literal and allow the other quote (and escape sequences) inside.
  const staticAssetsRegex = /staticAssets\s*\(\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)")\s*\)/g;
  for (const match of code.matchAll(staticAssetsRegex)) {
    const rawAssetPath = match[1] ?? match[2];
    // Unescape the captured value: \', \", and \\ are the only escapes we
    // need to undo for a path-like literal.
    const assetPath = rawAssetPath.replace(/\\(['"\\])/g, '$1');
    if (!currentFiles.has(assetPath)) {
      const relativeId = normalizePath(path.relative(process.cwd(), id));
      const relativeDir = normalizePath(path.relative(process.cwd(), directory));
      return `\n\n${styleText('red', 'Error:')} Static asset: ${styleText('yellowBright', assetPath)}\n  Referenced in: ${styleText('cyan', relativeId)}\n  Asset not found in scanned directory: ${styleText('blue', relativeDir)}\n\n  Please ensure the asset exists and the path is correct.\n`;
    }
  }

  return null;
}

// Export pure functions for testing
export { getAllFiles, extractDirectories, generateVirtualModuleCode, generateDtsCode, validateAssetReferences };

// --- Main Plugin Function ---

export default function staticAssetsPlugin(options: StaticAssetsPluginOptions = {}): Plugin {
  const ignorePatterns = options.ignore || ['.DS_Store'];
  const enableDirectoryTypes = options.enableDirectoryTypes !== false;
  const isIgnored = picomatch(ignorePatterns, { dot: true });

  if (options.addLeadingSlash !== undefined) {
    console.warn(`${styleText('yellow', '⚠')} [vite-plugin-static-assets] 'addLeadingSlash' is deprecated and ignored. Base URL is now handled automatically via import.meta.env.BASE_URL.`);
  }

  // Deprecation warning for `outputFile` fires at factory time (independent of
  // root resolution), matching the behavior of `addLeadingSlash`. The actual
  // path rewrite (.ts -> .d.ts) lives in resolvePaths.
  if (options.outputFile && !options.typesOutputFile) {
    console.warn(`${styleText('yellow', '⚠')} [vite-plugin-static-assets] 'outputFile' is deprecated. Use 'typesOutputFile' instead. The plugin now generates a .d.ts file, not a .ts file.`);
  }

  // Path resolution is deferred to configResolved so we can base it on
  // resolvedConfig.root (which respects Vite's `root` option and the
  // directory the user actually invoked Vite from). Resolving against
  // process.cwd() at factory time silently scans the wrong public/ when
  // running e.g. `vite -c apps/web/vite.config.ts` from a parent dir or
  // with `root: 'app'` in config.
  //
  // Tests that drive plugin hooks directly without firing configResolved
  // get a process.cwd()-based fallback resolved on first use.
  let directory: string | null = null;
  let typesOutputFile: string | null = null;

  const resolvePaths = (root: string) => {
    directory = path.resolve(root, options.directory || 'public');
    if (options.typesOutputFile) {
      typesOutputFile = path.resolve(root, options.typesOutputFile);
    } else if (options.outputFile) {
      // Derive .d.ts path from old outputFile (deprecation warning already
      // emitted at factory time above)
      const oldPath = options.outputFile;
      typesOutputFile = path.resolve(root, oldPath.replace(/\.ts$/, '.d.ts'));
    } else {
      typesOutputFile = path.resolve(root, 'src/static-assets.d.ts');
    }
  };

  const ensurePathsResolved = () => {
    if (directory === null || typesOutputFile === null) {
      resolvePaths(process.cwd());
    }
  };

  // State
  let currentFiles: Set<string> = new Set();
  let debounceTimer: ReturnType<typeof setTimeout> | null = null;
  let server: ViteDevServer | null = null;
  let logger: Logger | null = null;
  // Bound watcher handler retained so it can be detached in cleanup. Using a
  // single shared handler keeps add/off pairings symmetrical.
  let registeredHandler: ((changedPath: string) => void) | null = null;
  // Detaches listeners and clears timers. Set in configureServer; called from
  // closeBundle and httpServer 'close'.
  let cleanup: (() => void) | null = null;
  const info = (msg: string) => {
    if (logger) logger.info(msg);
    else console.log(msg);
  };
  const warn = (msg: string) => {
    if (logger) logger.warn(msg);
    else console.warn(msg);
  };

  const writeDtsFile = async (files: string[]) => {
    ensurePathsResolved();
    const dtsCode = generateDtsCode(files, { ...options, enableDirectoryTypes });
    const outputDir = path.dirname(typesOutputFile!);
    await fs.promises.mkdir(outputDir, { recursive: true });

    // Only write if content changed
    const currentContent = await fs.promises.readFile(typesOutputFile!, 'utf-8').catch(() => '');
    if (currentContent !== dtsCode) {
      await fs.promises.writeFile(typesOutputFile!, dtsCode);
      return true;
    }
    return false;
  };

  return {
    name: 'vite-plugin-static-assets',

    configResolved(resolvedConfig) {
      logger = resolvedConfig.logger;
      resolvePaths(resolvedConfig.root);
    },

    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID;
      }
    },

    load(id) {
      if (id === RESOLVED_VIRTUAL_MODULE_ID) {
        return generateVirtualModuleCode([...currentFiles]);
      }
    },

    async buildStart() {
      try {
        ensurePathsResolved();
        // Stat the source. ENOENT is a soft warning (some workflows scan a
        // directory that doesn't exist yet); any other access error or a
        // non-directory target is a hard failure — silently emitting empty
        // types would hide the misconfiguration.
        let sourceExists = false;
        try {
          const stat = await fs.promises.stat(directory!);
          if (!stat.isDirectory()) {
            throw new Error(
              `[vite-plugin-static-assets] 'directory' option "${options.directory || 'public'}" is not a directory.`,
            );
          }
          sourceExists = true;
        } catch (e) {
          const error = e as NodeJS.ErrnoException;
          if (error.code === 'ENOENT') {
            warn(`${styleText('yellow', '⚠')} [vite-plugin-static-assets] Source directory "${options.directory || 'public'}" not found. Generating empty types.`);
            currentFiles = new Set();
          } else {
            throw e;
          }
        }

        // Scan files
        const files = sourceExists ? await getAllFiles(directory!, directory!, isIgnored) : [];

        currentFiles = new Set(files);

        // Write .d.ts file
        await writeDtsFile(files);
        info(`${styleText('green', '✓')} Generated static assets types at ${styleText('blue', normalizePath(path.relative(process.cwd(), typesOutputFile!)))} (${currentFiles.size} assets)`);
      } catch (err) {
        console.error(`${styleText('red', '✗')} [vite-plugin-static-assets] Error during buildStart: ${err instanceof Error ? err.message : err}`);
        throw err;
      }
    },

    transform(code: string, id: string) {
      // Skip node_modules and any virtual module (ours or another plugin's —
      // virtual ids are conventionally prefixed with `\0`).
      if (id.includes('node_modules') || id.startsWith('\0')) {
        return null;
      }
      // Strip the query string before extension matching. Vite passes SFC
      // sub-block ids with queries (e.g. `App.vue?vue&type=template`) and
      // virtual-id suffixes (`foo.tsx?virtual`); the `$` anchor would
      // otherwise let those slip past validation silently.
      const cleanId = id.split('?')[0];
      // Only process relevant files. Covers JS/TS (with esm/cjs variants),
      // Vue/Svelte SFCs, and Astro/MDX components.
      if (!/\.(?:[mc]?[jt]sx?|vue|svelte|astro|mdx)$/.test(cleanId)) {
        return null;
      }

      ensurePathsResolved();
      const error = validateAssetReferences(code, id, currentFiles, directory!, options);
      if (error) {
        console.error(error);
        throw new Error(error);
      }

      return null;
    },

    configureServer(devServer) {
      server = devServer;
      ensurePathsResolved();

      // Use Vite's built-in watcher instead of a separate chokidar instance
      server.watcher.add(directory!);

      // Normalized directory + separator for path-prefix gating. Vite normalizes
      // chokidar event paths to POSIX, but we accept either separator defensively.
      const normalizedDirectory = normalizePath(directory!);
      const isInsideDirectory = (changedPath: string): boolean => {
        if (!changedPath) return false;
        const normalized = normalizePath(changedPath);
        if (normalized === normalizedDirectory) return true;
        return normalized.startsWith(`${normalizedDirectory}/`);
      };

      // Serialize rescans: a new debounce firing while a previous rescan is
      // still running awaits it, so we never race on `currentFiles` or the dts
      // write. clearTimeout cancels pending debounces; this awaits in-flight ones.
      let inFlight: Promise<void> | null = null;

      const runRescan = async () => {
        try {
          info(`${styleText('cyan', 'ℹ')} [vite-plugin-static-assets] Change detected, regenerating types...`);
          const updatedFiles = await getAllFiles(directory!, directory!, isIgnored);
          const newFileSet = new Set(updatedFiles);

          // Short-circuit if file set hasn't changed
          if (newFileSet.size === currentFiles.size && [...newFileSet].every(f => currentFiles.has(f))) {
            info(`${styleText('gray', '✓')} [vite-plugin-static-assets] No changes in asset set.`);
            return;
          }

          currentFiles = newFileSet;

          // Regenerate .d.ts
          await writeDtsFile(updatedFiles);

          // Server may have been torn down while we were awaiting I/O. Touching
          // a stale moduleGraph would crash with a confusing error.
          if (!server) return;
          const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID);
          if (mod) {
            server.moduleGraph.invalidateModule(mod);
          }
          server.ws.send({ type: 'full-reload' });

          info(`${styleText('green', '✓')} Updated static assets type definitions — ${currentFiles.size} assets.`);
        } catch (err) {
          console.error(`${styleText('red', '✗')} Error updating static assets: ${err instanceof Error ? err.message : err}`);
        }
      };

      const handleChange = (changedPath: string) => {
        // server.watcher is Vite's project-wide chokidar — every src/ save
        // would otherwise trigger a full rescan of `directory`. Gate at the
        // top so the debounce timer is only armed for genuine asset events.
        if (!isInsideDirectory(changedPath)) return;
        if (debounceTimer) clearTimeout(debounceTimer);
        debounceTimer = setTimeout(() => {
          debounceTimer = null;
          const prev = inFlight;
          const current: Promise<void> = (async () => {
            if (prev) {
              try { await prev; } catch { /* prior failure already logged */ }
            }
            await runRescan();
          })();
          inFlight = current;
          // Only clear `inFlight` if no later rescan has replaced us; this
          // avoids racing a subsequent debounce that overwrote `inFlight`.
          current.finally(() => {
            if (inFlight === current) inFlight = null;
          });
        }, options.debounce ?? 200);
      };

      // buildEnd is a Rollup hook and doesn't fire when a Vite dev server stops
      // (only closeBundle and httpServer 'close' do). Leaving listeners attached
      // would leak across server.restart() and let stale callbacks touch a torn-
      // down server. Track handlers and detach them in cleanup.
      server.watcher.on('add', handleChange);
      server.watcher.on('unlink', handleChange);
      server.watcher.on('change', handleChange);
      server.watcher.on('addDir', handleChange);
      server.watcher.on('unlinkDir', handleChange);

      registeredHandler = handleChange;
      cleanup = () => {
        if (debounceTimer) {
          clearTimeout(debounceTimer);
          debounceTimer = null;
        }
        if (server && registeredHandler) {
          server.watcher.off('add', registeredHandler);
          server.watcher.off('unlink', registeredHandler);
          server.watcher.off('change', registeredHandler);
          server.watcher.off('addDir', registeredHandler);
          server.watcher.off('unlinkDir', registeredHandler);
        }
        registeredHandler = null;
        server = null;
      };

      server.httpServer?.once('close', () => {
        cleanup?.();
        cleanup = null;
      });

      info(`${styleText('cyan', 'ℹ')} [vite-plugin-static-assets] Watching for changes in ${styleText('blue', normalizePath(path.relative(process.cwd(), directory!)))}`);
    },

    closeBundle() {
      // Dev-server teardown path: closeBundle fires; httpServer 'close' may
      // also fire. Either path runs cleanup; the second call is a no-op.
      cleanup?.();
      cleanup = null;
    },

    buildEnd() {
      // Rollup build path (vite build): no watcher was registered, but if a
      // debounce timer somehow exists we still cancel it.
      if (debounceTimer) {
        clearTimeout(debounceTimer);
        debounceTimer = null;
      }
    },
  };
}
